In [1]:
import pandas as pd
import numpy as np

In [2]:
import keras
import tensorflow as tf
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import *
from keras.layers import *
from keras.callbacks import *

In [3]:
train =pd.read_csv('/Train.csv', encoding = "utf8")

In [4]:
valid =pd.read_csv('/Valid.csv', encoding = "utf8")

In [5]:
x_tr, y_tr = train['text'].values, train['label'].values
x_val, y_val = valid['text'].values, valid['label'].values

In [6]:
x_tr.size

40000

In [7]:
 y_tr.size

40000

In [8]:
x_val.size

5000

In [9]:
y_val.size

5000

In [10]:
tokenizer = Tokenizer()

In [11]:
t = tokenizer.fit_on_texts(list(x_tr))

In [12]:
x_tr_se = tokenizer.texts_to_sequences(x_tr)
x_val_se = tokenizer.texts_to_sequences(x_val)

In [13]:
x_tr_seq= pad_sequences(x_tr_se, maxlen=100)
x_val_seq= pad_sequences(x_val_se, maxlen=100)

In [14]:
x_tr_seq.shape

(40000, 100)

In [15]:
x_val_seq.shape

(5000, 100)

In [16]:
size_of_vocabulary = len(tokenizer.word_index)+1
print(size_of_vocabulary)

112204


In [17]:
print(tokenizer.word_index)

{'the': 1, 'and': 2, 'a': 3, 'of': 4, 'to': 5, 'is': 6, 'br': 7, 'in': 8, 'it': 9, 'i': 10, 'this': 11, 'that': 12, 'was': 13, 'as': 14, 'for': 15, 'movie': 16, 'with': 17, 'but': 18, 'film': 19, 'on': 20, 'you': 21, 'not': 22, 'are': 23, 'his': 24, 'have': 25, 'be': 26, 'one': 27, 'he': 28, 'all': 29, 'at': 30, 'by': 31, 'an': 32, 'they': 33, 'so': 34, 'who': 35, 'from': 36, 'like': 37, 'or': 38, 'just': 39, 'her': 40, 'about': 41, 'out': 42, 'if': 43, "it's": 44, 'has': 45, 'there': 46, 'some': 47, 'what': 48, 'good': 49, 'more': 50, 'when': 51, 'very': 52, 'up': 53, 'no': 54, 'time': 55, 'even': 56, 'my': 57, 'would': 58, 'she': 59, 'which': 60, 'only': 61, 'really': 62, 'see': 63, 'story': 64, 'their': 65, 'had': 66, 'can': 67, 'me': 68, 'were': 69, 'well': 70, 'much': 71, 'than': 72, 'we': 73, 'been': 74, 'get': 75, 'bad': 76, 'will': 77, 'also': 78, 'do': 79, 'other': 80, 'great': 81, 'into': 82, 'people': 83, 'because': 84, 'him': 85, 'how': 86, 'first': 87, 'most': 88, "don't":

In [18]:
model = Sequential()

In [19]:
model.add(Embedding(size_of_vocabulary, 300, input_length=100, trainable = True))

In [20]:
model.add(LSTM(128, return_sequences= True, dropout = 0.2))

In [21]:
model.add(GlobalMaxPool1D())

In [22]:
model.add(Dense(64, activation ='relu'))
model.add(Dense(1, activation= 'sigmoid'))

In [23]:
model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['acc'])

In [24]:
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience=3)
mc=ModelCheckpoint('best_model.h5', monitor='val_acc', mode='max', save_best_only=True,verbose=1)

In [25]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 100, 300)          33661200  
_________________________________________________________________
lstm (LSTM)                  (None, 100, 128)          219648    
_________________________________________________________________
global_max_pooling1d (Global (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 33,889,169
Trainable params: 33,889,169
Non-trainable params: 0
_________________________________________________________________
None


In [26]:
history = model.fit(x_tr_seq, y_tr, batch_size=128, epochs=2, validation_data= (x_val_seq, y_val), verbose=1, callbacks=[es,mc])

Epoch 1/2
313/313 [==============================] - 124s 324ms/step - loss: 0.5203 - acc: 0.7082 - val_loss: 0.3133 - val_acc: 0.8668

Epoch 00001: val_acc improved from -inf to 0.86680, saving model to best_model.h5
Epoch 2/2
313/313 [==============================] - 101s 322ms/step - loss: 0.1978 - acc: 0.9257 - val_loss: 0.3391 - val_acc: 0.8540

Epoch 00002: val_acc did not improve from 0.86680


In [28]:
from keras.models import load_model
model = load_model('best_model.h5')

In [29]:
val_acc = model.evaluate(x_val_seq,y_val, batch_size=128)
print(val_acc)

40/40 [==============================] - 1s 12ms/step - loss: 0.3133 - acc: 0.8668
[0.3132990598678589, 0.8668000102043152]


In [30]:
import tensorflow as tf

In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [32]:
import string

In [33]:
import nltk

In [34]:
from nltk.tokenize import word_tokenize

In [35]:
from nltk.corpus import stopwords

In [36]:
df = pd.concat([train, valid], axis =0)

In [38]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [39]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [42]:
text_lines = list()
lines = df['text'].values.tolist()

In [43]:
for line in lines:
  tokens = word_tokenize(str(line))
  tokens = [w.lower() for w in tokens]
  table = str.maketrans('', '', string.punctuation)
  stripped = [w.translate(table) for w in tokens]
  words = [word for word in stripped if word.isalpha()]
  stop_words =set(stopwords.words('english'))
  words =[w for w in words if not w in stop_words]
  text_lines.append(words)

In [44]:
len(text_lines)

45000

In [45]:
import gensim

In [46]:
model = gensim.models.Word2Vec(sentences= text_lines, size =100, window =5, workers =4, min_count = 2)

In [47]:
words = list(model.wv.vocab)

In [48]:
print(model) 

Word2Vec(vocab=65181, size=100, alpha=0.025)


In [49]:
print('vocabulary size: %d' % len(words))

vocabulary size: 65181


In [51]:
model.most_similar('cool')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('awesome', 0.6941536664962769),
 ('neat', 0.6632729768753052),
 ('nice', 0.6564593315124512),
 ('weird', 0.6507539749145508),
 ('cheesy', 0.6377196311950684),
 ('good', 0.6010268330574036),
 ('freaky', 0.6003487706184387),
 ('goofy', 0.5937083959579468),
 ('liked', 0.5906673073768616),
 ('super', 0.5871202945709229)]

In [52]:
filename = 'word_embeddings_for_imdb_word2vec.txt'

In [53]:
model.wv.save_word2vec_format(filename, binary = False)

In [54]:
import os

In [55]:
embeddings_index = {}
f = open(os.path.join('', 'word_embeddings_for_imdb_word2vec.txt'), encoding ="utf-8")
for line in f:
  values =line.split()
  word =values[0]
  coefs = np.asarray(values[1:])
  embeddings_index[word] = coefs
f.close()  

In [59]:
coefs

array(['0.011921617', '0.028200375', '0.02815127', '-0.022570629',
       '-0.013221987', '-0.048365694', '-0.016263226', '-0.013098148',
       '-0.0047104303', '0.0016001529', '0.031271555', '0.016399598',
       '-0.02646073', '-0.034254037', '-0.024894547', '-0.011866967',
       '-0.013397034', '0.014115532', '-0.0017585899', '-0.028002925',
       '0.005427765', '0.028051324', '-0.024445001', '0.02201389',
       '-0.013365416', '0.03240912', '-0.012431998', '-0.0068862634',
       '0.00768793', '-0.0037086636', '-0.01143038', '-0.0071794163',
       '-0.028575296', '0.03883015', '0.031420045', '0.044937704',
       '-0.021542503', '0.00871583', '0.010271718', '0.012805026',
       '-0.002258475', '0.0026410243', '0.0049885768', '-0.009339508',
       '0.01357256', '-0.014778', '-0.019311689', '0.0043162606',
       '-0.025120798', '-0.034027126', '-0.0040652393', '0.008774415',
       '-0.003641417', '-0.012392265', '-0.015747497', '0.010202261',
       '0.038044516', '-0.036437

In [60]:
 embeddings_index[word]

array(['0.011921617', '0.028200375', '0.02815127', '-0.022570629',
       '-0.013221987', '-0.048365694', '-0.016263226', '-0.013098148',
       '-0.0047104303', '0.0016001529', '0.031271555', '0.016399598',
       '-0.02646073', '-0.034254037', '-0.024894547', '-0.011866967',
       '-0.013397034', '0.014115532', '-0.0017585899', '-0.028002925',
       '0.005427765', '0.028051324', '-0.024445001', '0.02201389',
       '-0.013365416', '0.03240912', '-0.012431998', '-0.0068862634',
       '0.00768793', '-0.0037086636', '-0.01143038', '-0.0071794163',
       '-0.028575296', '0.03883015', '0.031420045', '0.044937704',
       '-0.021542503', '0.00871583', '0.010271718', '0.012805026',
       '-0.002258475', '0.0026410243', '0.0049885768', '-0.009339508',
       '0.01357256', '-0.014778', '-0.019311689', '0.0043162606',
       '-0.025120798', '-0.034027126', '-0.0040652393', '0.008774415',
       '-0.003641417', '-0.012392265', '-0.015747497', '0.010202261',
       '0.038044516', '-0.036437

In [61]:
tokenizer_obj = Tokenizer()
tokenizer_obj.fit_on_texts(text_lines)
sequences= tokenizer_obj.texts_to_sequences(text_lines)


In [62]:
word_index = tokenizer_obj.word_index
print('Found %s unique tokens.' % len(word_index))

Found 127151 unique tokens.


In [64]:
text_pad = pad_sequences(sequences,  maxlen= 100)
label = df['label'].values

In [65]:
print('shape of review tesor:', text_pad.shape)
print('shape of sentiment tensor:', label.shape)

shape of review tesor: (45000, 100)
shape of sentiment tensor: (45000,)


In [66]:
num_words= len(word_index)+1
embedding_matrix = np.zeros((num_words, 100))
for word, i in word_index.items():
  if i > num_words:
    continue 
    embedding_vector = embedding_index.get(word)
    if embedding_vector is not None:
      embedding_matrix[i] = embedding_vecor

In [67]:
num_words

127152

In [68]:
embedding_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [69]:
print(num_words)

127152


In [70]:
from keras.models import Sequential 
from keras.initializers import Constant

In [71]:
model1 = Sequential()

In [72]:
model1.add(Embedding(num_words, 100, embeddings_initializer=Constant(embedding_matrix), input_length =100,  trainable =False))
model1.add(GRU(units =32, recurrent_dropout=0.2))
model1.add(Dense(1, activation = 'sigmoid'))

In [73]:
model1.compile(loss ='binary_crossentropy', optimizer = 'adam', metrics =['accuracy'])

In [74]:
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 100)          12715200  
_________________________________________________________________
gru (GRU)                    (None, 32)                12864     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 12,728,097
Trainable params: 12,897
Non-trainable params: 12,715,200
_________________________________________________________________
None


In [75]:
model1.fit(x_tr_seq, y_tr, batch_size =128, epochs =2, validation_data =(x_val_seq, y_val), verbose =2)

Epoch 1/2
313/313 - 85s - loss: 0.6932 - accuracy: 0.5006 - val_loss: 0.6931 - val_accuracy: 0.5028
Epoch 2/2
313/313 - 76s - loss: 0.6932 - accuracy: 0.4982 - val_loss: 0.6931 - val_accuracy: 0.5028


In [76]:
!wget http://nlp.stanford.edu/data/glove.6B.zip

--2021-07-02 20:36:51--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2021-07-02 20:36:51--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2021-07-02 20:36:51--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [77]:
!unzip glove*.zip

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [78]:
!ls
!pwd

best_model.h5	   glove.6B.300d.txt  sample_data
glove.6B.100d.txt  glove.6B.50d.txt   word_embeddings_for_imdb_word2vec.txt
glove.6B.200d.txt  glove.6B.zip
/content


In [79]:
embeddings_index = dict()
f = open('glove.6B.100d.txt', encoding='utf-8')

In [80]:
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


In [81]:
values[0]

'sandberger'

In [83]:
values[1:]

['0.28365',
 '-0.6263',
 '-0.44351',
 '0.2177',
 '-0.087421',
 '-0.17062',
 '0.29266',
 '-0.024899',
 '0.26414',
 '-0.17023',
 '0.25817',
 '0.097484',
 '-0.33103',
 '-0.43859',
 '0.0095799',
 '0.095624',
 '-0.17777',
 '0.38886',
 '0.27151',
 '0.14742',
 '-0.43973',
 '-0.26588',
 '-0.024271',
 '0.27186',
 '-0.36761',
 '-0.24827',
 '-0.20815',
 '0.22128',
 '-0.044409',
 '0.021373',
 '0.24594',
 '0.26143',
 '0.29303',
 '0.13281',
 '0.082232',
 '-0.12869',
 '0.1622',
 '-0.22567',
 '-0.060348',
 '0.28703',
 '0.11381',
 '0.34839',
 '0.3419',
 '0.36996',
 '-0.13592',
 '0.0062694',
 '0.080317',
 '0.0036251',
 '0.43093',
 '0.01882',
 '0.31008',
 '0.16722',
 '0.074112',
 '-0.37745',
 '0.47363',
 '0.41284',
 '0.24471',
 '0.075965',
 '-0.51725',
 '-0.49481',
 '0.526',
 '-0.074645',
 '0.41434',
 '-0.1956',
 '-0.16544',
 '-0.045649',
 '-0.40153',
 '-0.13136',
 '-0.4672',
 '0.18825',
 '0.2612',
 '0.16854',
 '0.22615',
 '0.62992',
 '-0.1288',
 '0.055841',
 '0.01928',
 '0.024572',
 '0.46875',
 '0.2582'

In [84]:
embeddings_index[word]

array([ 0.28365  , -0.6263   , -0.44351  ,  0.2177   , -0.087421 ,
       -0.17062  ,  0.29266  , -0.024899 ,  0.26414  , -0.17023  ,
        0.25817  ,  0.097484 , -0.33103  , -0.43859  ,  0.0095799,
        0.095624 , -0.17777  ,  0.38886  ,  0.27151  ,  0.14742  ,
       -0.43973  , -0.26588  , -0.024271 ,  0.27186  , -0.36761  ,
       -0.24827  , -0.20815  ,  0.22128  , -0.044409 ,  0.021373 ,
        0.24594  ,  0.26143  ,  0.29303  ,  0.13281  ,  0.082232 ,
       -0.12869  ,  0.1622   , -0.22567  , -0.060348 ,  0.28703  ,
        0.11381  ,  0.34839  ,  0.3419   ,  0.36996  , -0.13592  ,
        0.0062694,  0.080317 ,  0.0036251,  0.43093  ,  0.01882  ,
        0.31008  ,  0.16722  ,  0.074112 , -0.37745  ,  0.47363  ,
        0.41284  ,  0.24471  ,  0.075965 , -0.51725  , -0.49481  ,
        0.526    , -0.074645 ,  0.41434  , -0.1956   , -0.16544  ,
       -0.045649 , -0.40153  , -0.13136  , -0.4672   ,  0.18825  ,
        0.2612   ,  0.16854  ,  0.22615  ,  0.62992  , -0.1288

In [85]:
embedding_matrix = np.zeros((size_of_vocabulary, 100))
 
for word, i in tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [86]:
embedding_matrix[1]

array([-0.038194  , -0.24487001,  0.72812003, -0.39961001,  0.083172  ,
        0.043953  , -0.39140999,  0.3344    , -0.57545   ,  0.087459  ,
        0.28786999, -0.06731   ,  0.30906001, -0.26383999, -0.13231   ,
       -0.20757   ,  0.33395001, -0.33848   , -0.31742999, -0.48335999,
        0.1464    , -0.37303999,  0.34577   ,  0.052041  ,  0.44946   ,
       -0.46970999,  0.02628   , -0.54154998, -0.15518001, -0.14106999,
       -0.039722  ,  0.28277001,  0.14393   ,  0.23464   , -0.31020999,
        0.086173  ,  0.20397   ,  0.52623999,  0.17163999, -0.082378  ,
       -0.71787   , -0.41531   ,  0.20334999, -0.12763   ,  0.41367   ,
        0.55186999,  0.57907999, -0.33476999, -0.36559001, -0.54856998,
       -0.062892  ,  0.26583999,  0.30204999,  0.99774998, -0.80480999,
       -3.0243001 ,  0.01254   , -0.36941999,  2.21670008,  0.72201002,
       -0.24978   ,  0.92136002,  0.034514  ,  0.46744999,  1.10790002,
       -0.19358   , -0.074575  ,  0.23353   , -0.052062  , -0.22

In [87]:
embedding_matrix[i]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
model=Sequential()

In [89]:
model.add(Embedding(size_of_vocabulary,100,weights=[embedding_matrix],input_length=100,trainable=False))

In [90]:
model.add(LSTM(128,return_sequences=True,dropout=0.2))

In [91]:
model.add(GlobalMaxPooling1D())

In [92]:
model.add(Dense(64,activation='relu')) 
model.add(Dense(1,activation='sigmoid'))

In [93]:
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=["acc"])

In [94]:
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience=3)  
mc=ModelCheckpoint('best_model.h5', monitor='val_acc', mode='max', save_best_only=True,verbose=1) 

In [95]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 100, 100)          11220400  
_________________________________________________________________
lstm_1 (LSTM)                (None, 100, 128)          117248    
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 128)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65        
Total params: 11,345,969
Trainable params: 125,569
Non-trainable params: 11,220,400
_________________________________________________________________
None


In [96]:
history = model.fit(x_tr_seq, y_tr, batch_size=128, epochs=2, validation_data= (x_val_seq, y_val), verbose=1, callbacks=[es,mc])

Epoch 1/2
313/313 [==============================] - 6s 13ms/step - loss: 0.5883 - acc: 0.6626 - val_loss: 0.3919 - val_acc: 0.8240

Epoch 00001: val_acc improved from -inf to 0.82400, saving model to best_model.h5
Epoch 2/2
313/313 [==============================] - 3s 11ms/step - loss: 0.4030 - acc: 0.8138 - val_loss: 0.3540 - val_acc: 0.8438

Epoch 00002: val_acc improved from 0.82400 to 0.84380, saving model to best_model.h5


In [97]:
from keras.models import load_model
model = load_model('best_model.h5')
_,val_acc = model.evaluate(x_val_seq,y_val, batch_size=128)
print(val_acc)

40/40 [==============================] - 1s 8ms/step - loss: 0.3540 - acc: 0.8438
0.8438000082969666
